-- liquibase formatted sql

-- changeset init:create-countries
CREATE TABLE IF NOT EXISTS countries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(2) NOT NULL,
    UNIQUE (name),
    UNIQUE (code)
);

-- changeset init:create-regions
CREATE TABLE IF NOT EXISTS regions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    country_id BIGINT,
    parent_id BIGINT,
    FOREIGN KEY (country_id) REFERENCES countries(id),
    FOREIGN KEY (parent_id) REFERENCES regions(id)
);

-- changeset init:create-political-parties
CREATE TABLE IF NOT EXISTS political_parties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    ideology VARCHAR(255),
    founded_date DATE,
    headquarters VARCHAR(255),
    logo_url VARCHAR(255),
    description TEXT,
    UNIQUE (name)
);

-- changeset init:create-party-regions
CREATE TABLE IF NOT EXISTS party_regions (
    party_id BIGINT NOT NULL,
    region_id BIGINT NOT NULL,
    PRIMARY KEY (party_id, region_id),
    FOREIGN KEY (party_id) REFERENCES political_parties(id),
    FOREIGN KEY (region_id) REFERENCES regions(id)
);

-- changeset init:create-nomination-costs
CREATE TABLE IF NOT EXISTS nomination_costs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_type VARCHAR(50) NOT NULL,
    amount DECIMAL(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'INR',
    country_id BIGINT NOT NULL,
    UNIQUE (region_type, country_id),
    FOREIGN KEY (country_id) REFERENCES countries(id)
);

-- changeset init:create-party-members
CREATE TABLE IF NOT EXISTS party_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(255),
    role VARCHAR(255),
    date_of_birth DATE,
    join_date DATE,
    active BOOLEAN DEFAULT TRUE,
    party_id BIGINT,
    UNIQUE (email),
    FOREIGN KEY (party_id) REFERENCES political_parties(id)
);
