-- liquibase formatted sql

-- ============================================================
-- KERALA
-- ============================================================
-- changeset init:seed-kl-ls
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kasaragod (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kannur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Vatakara (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Wayanad (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kozhikode (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Malappuram (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ponnani (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Palakkad (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Alathur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Thrissur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Chalakudy (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ernakulam (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Idukki (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kottayam (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Alappuzha (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mavelikkara (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Pathanamthitta (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kollam (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Attingal (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Thiruvananthapuram (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Kerala' AND s.type='STATE';
-- changeset init:seed-kl-vs
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kasaragod Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Kasaragod (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kannur City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Kannur (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Vatakara Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Vatakara (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Wayanad Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Wayanad (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kozhikode City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Kozhikode (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Malappuram Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Malappuram (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ponnani Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Ponnani (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Palakkad Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Palakkad (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Alathur Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Alathur (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Thrissur City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Thrissur (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Chalakudy Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Chalakudy (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ernakulam City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Ernakulam (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kochi City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Ernakulam (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Idukki Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Idukki (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Munnar (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Idukki (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kottayam City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Kottayam (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Alappuzha City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Alappuzha (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mavelikkara Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Mavelikkara (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Pathanamthitta Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Pathanamthitta (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kollam City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Kollam (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Attingal Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Attingal (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Thiruvananthapuram City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Thiruvananthapuram (Lok Sabha)' AND s.name='Kerala' AND ls.parent_id=s.id;

-- ============================================================
-- MADHYA PRADESH
-- ============================================================
-- changeset init:seed-mp-ls
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Morena (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Bhind (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Gwalior (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Guna (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Sagar (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Tikamgarh (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Damoh (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Khajuraho (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Satna (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Rewa (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Shahdol (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Sidhi (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Jabalpur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mandla (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Balaghat (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Chhindwara (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Hoshangabad (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Vidisha (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Bhopal (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Raisen (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Rajgarh (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Sehore (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Indore (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ujjain (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Dewas (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mandsaur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ratlam (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Dhar (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Khandwa (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Madhya Pradesh' AND s.type='STATE';
-- changeset init:seed-mp-vs
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Morena Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Morena (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Bhind Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Bhind (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Gwalior City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Gwalior (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Guna Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Guna (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Sagar City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Sagar (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Tikamgarh Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Tikamgarh (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Damoh Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Damoh (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Khajuraho Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Khajuraho (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Satna City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Satna (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Rewa City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Rewa (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Shahdol Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Shahdol (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Sidhi Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Sidhi (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Jabalpur City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Jabalpur (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Jabalpur West (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Jabalpur (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mandla Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Mandla (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Balaghat Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Balaghat (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Chhindwara Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Chhindwara (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Hoshangabad Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Hoshangabad (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Vidisha Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Vidisha (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Bhopal City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Bhopal (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Bhopal North (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Bhopal (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Raisen Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Raisen (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Rajgarh Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Rajgarh (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Sehore Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Sehore (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Indore City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Indore (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Indore South (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Indore (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ujjain City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Ujjain (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Dewas Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Dewas (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mandsaur Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Mandsaur (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ratlam Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Ratlam (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Dhar Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Dhar (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Khandwa Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Khandwa (Lok Sabha)' AND s.name='Madhya Pradesh' AND ls.parent_id=s.id;

-- ============================================================
-- MAHARASHTRA (abbreviated sample)
-- ============================================================
-- changeset init:seed-mh-ls
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Nandurbar (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Dhule (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Jalgaon (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Raver (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Buldhana (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Akola (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Amravati (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Wardha (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ramtek (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Nagpur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Bhandara-Gondiya (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Gadchiroli-Chimur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Chandrapur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Yavatmal-Washim (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Hingoli (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Nanded (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Parbhani (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Jalna (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Aurangabad (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Dindori (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Nashik (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Palghar (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Bhiwandi (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kalyan (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Thane (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mumbai North (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mumbai North West (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mumbai North East (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mumbai North Central (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mumbai South Central (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mumbai South (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Raigad (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Pune (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Baramati (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Shirur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ahmednagar (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Shirdi (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Beed (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Osmanabad (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Latur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Solapur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Madha (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Sangli (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Satara (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ratnagiri-Sindhudurg (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kolhapur (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Hatkanangale (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Maval (Lok Sabha)', 'LOK_SABHA', c.id, s.id FROM countries c, regions s WHERE c.code='IN' AND s.name='Maharashtra' AND s.type='STATE';
-- changeset init:seed-mh-vs
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Dhule Town (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Dhule (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Jalgaon City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Jalgaon (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Akola City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Akola (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Amravati City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Amravati (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Nagpur West (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Nagpur (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Nagpur East (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Nagpur (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Aurangabad City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Aurangabad (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Nashik Central (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Nashik (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Thane City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Thane (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Mumbai Central (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Mumbai North (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Pune Cantonment (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Pune (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Shivajinagar (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Pune (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Solapur City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Solapur (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Kolhapur City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Kolhapur (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Nanded City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Nanded (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Latur City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Latur (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Sangli City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Sangli (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
INSERT INTO regions (name, type, country_id, parent_id) SELECT 'Ahmednagar City (Vidhan Sabha)', 'VIDHAN_SABHA', c.id, ls.id FROM countries c, regions ls, regions s WHERE c.code='IN' AND ls.name='Ahmednagar (Lok Sabha)' AND s.name='Maharashtra' AND ls.parent_id=s.id;
